#!/usr/bin/env bash
set -euo pipefail

# PostgreSQL Migration Script for postgres
# Generated by compose2k8s
#
# This script helps migrate data from a Docker Compose PostgreSQL instance
# to a Kubernetes PostgreSQL instance.

NAMESPACE="fullstack"
SERVICE="postgres"
DB_USER="user"
DB_NAME="myapp"
DUMP_FILE="pg_dump_${DB_NAME}_$(date +%Y%m%d_%H%M%S).sql"

echo "=== PostgreSQL Migration: postgres ==="

# Step 1: Dump from source (Docker Compose)
echo "[1/3] Dumping database from Docker Compose..."
echo "  Run on your Docker host:"
echo "    docker compose exec postgres pg_dump -U ${DB_USER} -d ${DB_NAME} > ${DUMP_FILE}"
echo ""

# Step 2: Copy dump to K8s pod
echo "[2/3] Copying dump to Kubernetes pod..."
POD=$(kubectl get pods -n ${NAMESPACE} -l app.kubernetes.io/name=${SERVICE} -o jsonpath='{.items[0].metadata.name}')
echo "  kubectl cp ${DUMP_FILE} ${NAMESPACE}/${POD}:/tmp/${DUMP_FILE}"
echo ""

# Step 3: Restore in K8s
echo "[3/3] Restoring database in Kubernetes..."
echo "  kubectl exec -n ${NAMESPACE} ${POD} -- psql -U ${DB_USER} -d ${DB_NAME} -f /tmp/${DUMP_FILE}"
echo ""

echo "=== Migration steps printed. Review and execute manually. ==="
echo ""
echo "Or run the full automated migration:"
echo "  docker compose exec postgres pg_dump -U ${DB_USER} -d ${DB_NAME} > ${DUMP_FILE}"
echo "  kubectl cp ${DUMP_FILE} ${NAMESPACE}/${POD}:/tmp/${DUMP_FILE}"
echo "  kubectl exec -n ${NAMESPACE} ${POD} -- psql -U ${DB_USER} -d ${DB_NAME} -f /tmp/${DUMP_FILE}"
