#!/usr/bin/env bash
# wait-for.sh — Robust dependency wait script
# Generated by compose2k8s
#
# Usage: wait-for.sh <host> <port> [timeout_seconds]
# Example: wait-for.sh postgres 5432 60

set -euo pipefail

HOST="${1:?Usage: wait-for.sh <host> <port> [timeout]}"
PORT="${2:?Usage: wait-for.sh <host> <port> [timeout]}"
TIMEOUT="${3:-60}"

echo "Waiting for ${HOST}:${PORT} (timeout: ${TIMEOUT}s)..."

start_time=$(date +%s)

while true; do
  if nc -z "${HOST}" "${PORT}" 2>/dev/null; then
    echo "${HOST}:${PORT} is available."
    exit 0
  fi

  elapsed=$(( $(date +%s) - start_time ))
  if [ "${elapsed}" -ge "${TIMEOUT}" ]; then
    echo "ERROR: Timeout waiting for ${HOST}:${PORT} after ${TIMEOUT}s"
    exit 1
  fi

  echo "Waiting for ${HOST}:${PORT}... (${elapsed}s elapsed)"
  sleep 2
done
