import type { GeneratedManifest } from '../types/k8s.js';
import type { WizardConfig } from '../types/config.js';

/**
 * Generate a README with deployment instructions.
 */
export function generateReadme(
  manifests: GeneratedManifest[],
  config: WizardConfig,
): string {
  const lines: string[] = [];
  const ns = config.deploy.namespace;

  lines.push('# Kubernetes Manifests');
  lines.push('');
  lines.push('Generated by compose2k8s');
  lines.push('');

  // Overview
  lines.push('## Generated Files');
  lines.push('');
  for (const m of manifests) {
    lines.push(`- \`${m.filename}\` — ${m.description}`);
  }
  lines.push('');

  // Apply instructions
  lines.push('## Apply');
  lines.push('');
  if (ns) {
    lines.push('```sh');
    lines.push(`kubectl create namespace ${ns} --dry-run=client -o yaml | kubectl apply -f -`);
    lines.push(`kubectl apply -f ${config.deploy.outputDir}/ -n ${ns}`);
    lines.push('```');
  } else {
    lines.push('```sh');
    lines.push(`kubectl apply -f ${config.deploy.outputDir}/`);
    lines.push('```');
  }
  lines.push('');

  // Secrets warning
  const secretManifests = manifests.filter(
    (m) => m.manifest.kind === 'Secret',
  );
  if (secretManifests.length > 0) {
    lines.push('## Secrets');
    lines.push('');
    lines.push('The following secrets contain `REPLACE_ME` placeholders that must be updated with real values before applying:');
    lines.push('');
    for (const s of secretManifests) {
      lines.push(`- \`${s.filename}\` — ${s.description}`);
    }
    lines.push('');
  }

  // Storage notes
  const pvcManifests = manifests.filter(
    (m) => m.manifest.kind === 'PersistentVolumeClaim',
  );
  const ssManifests = manifests.filter(
    (m) => m.manifest.kind === 'StatefulSet',
  );
  if (pvcManifests.length > 0 || ssManifests.length > 0) {
    lines.push('## Storage');
    lines.push('');
    lines.push('Ensure your cluster has a default StorageClass or specify one in the PVC/StatefulSet manifests.');
    lines.push('');
  }

  return lines.join('\n');
}
